spring:
  application:
    name: bot

  kafka:
    bootstrapServers: kafka:9092
    consumer:
      topic: weather

bot:
  name: MeteoNotifierBot
  token:

url:
  weather: http://weather:8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: basic

server:
  port: 8082