spring:
  application:
    name: bot
  kafka:
    bootstrapServers: kafka:9092
    consumer:
      topic: weather
      group-id: group1
      auto-offset-reset: earliest

bot:
  name: MeteoNotifierBot
  token:

url:
  weather: http://localhost:8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: basic

server:
  port: 8081